services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "8080:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=chrome-extension://*
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

volumes:
  ollama:
